name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ACR
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.AZURE_ACR_NAME }}.azurecr.io
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}

      - name: Set environment variables from GitHub secrets
        run: |
          echo "API_KEY=${{ secrets.FAKE_KEY }}" >> $GITHUB_ENV

      - name: Prepare build args
        id: prepare_build_args
        run: |
          build_args=""
          build_args="${build_args} --build-arg DB_HOST=${{ secrets.DB_HOST }}"
          build_args="${build_args} --build-arg NODE_ENV=${{ secrets.NODE_ENV }}"
          build_args="${build_args} --build-arg DB_PORT=${{ secrets.DB_PORT }}"
          build_args="${build_args} --build-arg DB_NAME=${{ secrets.DB_NAME }}"
          build_args="${build_args} --build-arg DB_USERNAME=${{ secrets.DB_USERNAME }}"
          build_args="${build_args} --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD }}"
          build_args="${build_args} --build-arg SSL_CERT=${{ secrets.SSL_CERT }}"
          echo "BUILD_ARGS=${build_args}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/craftpile:${{ github.sha }}
          file: ./Dockerfile
          cache-from: type=gha
          cache-to: type=gha, mode=max
          build-args: ${{ env.BUILD_ARGS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/craftpile:${{ github.sha }}
